// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaX86hPSdbaLj_nECvc2C_aCKLInqtkKo',
    appId: '1:933624721032:web:bf908843cc2301ca5a793d',
    messagingSenderId: '933624721032',
    projectId: 'mealplannerapp-65b06',
    authDomain: 'mealplannerapp-65b06.firebaseapp.com',
    storageBucket: 'mealplannerapp-65b06.firebasestorage.app',
    measurementId: 'G-74CNHKK36T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb2SoOhAuU4JK-WP0SzcTVDO_JiMGmpwU',
    appId: '1:933624721032:android:67fd5d8bcf28d66e5a793d',
    messagingSenderId: '933624721032',
    projectId: 'mealplannerapp-65b06',
    storageBucket: 'mealplannerapp-65b06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkmYNbeF24fRQkenckTM6554sOGUAyPMk',
    appId: '1:933624721032:ios:7ba46a951ea2c3bb5a793d',
    messagingSenderId: '933624721032',
    projectId: 'mealplannerapp-65b06',
    storageBucket: 'mealplannerapp-65b06.firebasestorage.app',
    iosClientId: '933624721032-1huvhcbped43m5qlrq3buolc96ee86da.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealPlannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkmYNbeF24fRQkenckTM6554sOGUAyPMk',
    appId: '1:933624721032:ios:7ba46a951ea2c3bb5a793d',
    messagingSenderId: '933624721032',
    projectId: 'mealplannerapp-65b06',
    storageBucket: 'mealplannerapp-65b06.firebasestorage.app',
    iosClientId: '933624721032-1huvhcbped43m5qlrq3buolc96ee86da.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaX86hPSdbaLj_nECvc2C_aCKLInqtkKo',
    appId: '1:933624721032:web:26c5bbebfa420a775a793d',
    messagingSenderId: '933624721032',
    projectId: 'mealplannerapp-65b06',
    authDomain: 'mealplannerapp-65b06.firebaseapp.com',
    storageBucket: 'mealplannerapp-65b06.firebasestorage.app',
    measurementId: 'G-603GEBCYZ1',
  );
}
