name: meal_planner_app
description: "A cross-platform meal planning application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.9.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.5+1
  
  # Local Storage
  sqflite: ^2.3.3
  path: ^1.9.0

  # Firebase Backend
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0

  # Desktop SQLite FFI
  sqflite_common_ffi: ^2.3.6
  
  # HTTP Requests
  http: ^1.5.0
  
  # Date Handling
  table_calendar: ^3.2.0
  intl: ^0.20.2
  
  # UI Components
  flutter_slidable: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  
  # Image Handling
  cached_network_image: ^3.3.1
  
  # Voice Features
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true